spec-version: 0.36.0

name:                aoc-utils
version:             0.1.0.0
github:              "mpilgrem/aoc-solutions/aoc-solutions"
license:             BSD-3-Clause
author:              "Mike Pilgrem"
maintainer:          "public@pilgrem.com"
copyright:           "Copyright 2025"

extra-source-files:
- README.md
- CHANGELOG.md

description: |
  Utilities for Advent of Code solutions.

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
